### ISSUE TITLE
Add Error Messages in API

### ISSUE THREAD

**Issue by simonschuhmacher** [saunah/saunah-backend#48]
## Goal

Up until now, for almost all errors in the backend, a default `500 Internal Server Error` is returned, if a API call is invalid. This makes debugging sometime quite hard. To facilitate debugging calls to the API, more specific error messages should be returned (e.g. based on exception messages).
[Example](https://www.baeldung.com/global-error-handler-in-a-spring-rest-api)

## Acceptance

**Comment by triumphvalley** [comment]
@NinoCabernard what is the maximum file size for an image upload? We have to make sure that we catch this errors also in the frontend.

**Comment by cabernin** [comment]
> @NinoCabernard what is the maximum file size for an image upload? We have to make sure that we catch this errors also in the frontend.

I believe we can set the maximum file size ourselves. I think we can set the maximum size to 50 MB

**Comment by triumphvalley** [comment]
> I believe we can set the maximum file size ourselves. I think we can set the maximum size to 50 MB

50 MB is probably a bit high, the images would load forever I guess? Maybe just 5MB?
